//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HypermarketList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Branch
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string bNo { get; set; }

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string cId { get; set; }

        [DisplayName("分店名稱")]
        public string bName { get; set; }

        [DisplayName("聯絡電話")]
        public string phone { get; set; }

        [DisplayName("分店地址")]
        public string address { get; set; }

        [DisplayName("營業時間")]
        public System.DateTime startTime { get; set; }

        [DisplayName("歇業時間")]
        public System.DateTime endTime { get; set; }
        
        public virtual Company Company { get; set; }
    }
}
