//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HypermarketList.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Member
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public string mId { get; set; }

        [DisplayName("會員帳號")]
        [Required(ErrorMessage = "帳號欄位不可為空")]
        [StringLength(10, ErrorMessage = "帳號必須是 5-10 個字元", MinimumLength = 5)]
        public string name { get; set; }

        [DisplayName("會員密碼")]
        [Required(ErrorMessage = "密碼欄位不可為空")]
        [StringLength(16, ErrorMessage = "密碼必須是 8-16 個字元", MinimumLength = 8)]
        public string password { get; set; }
    }
}
